let productData = [
  {
    img: "assets/images/product1.png",
    rating: "4.2",
    brand: "Zara",
    title: "Quilted gilet with hood",
    color: ["Red", "Blue", "Black", "Pink", "Purple"],
    size: ["XS", "X", "M"],
    price: "110",
  },
  {
    img: "assets/images/product1.png",
    rating: "4.8",
    brand: "Zara",
    title: "Quilted gilet with hood",
    color: ["Red", "Blue", "Black", "Pink", "Purple"],
    size: ["XS", "X", "M"],
    price: "180",
  },
  {
    img: "assets/images/product1.png",
    rating: "4.8",
    brand: "Zara",
    title: "Quilted gilet with hood",
    color: ["Red", "Blue", "Black", "Pink", "Purple"],
    size: ["XS", "X", "M"],
    price: "180",
  },
  {
    img: "assets/images/product1.png",
    rating: "4.8",
    brand: "Zara",
    title: "Quilted gilet with hood",
    color: ["Red", "Blue", "Black", "Pink", "Purple"],
    size: ["XS", "X", "M"],
    price: "180",
  },
  {
    img: "assets/images/product1.png",
    rating: "4.8",
    brand: "Zara",
    title: "Quilted gilet with hood",
    color: ["Red", "Blue", "Black", "Pink", "Purple"],
    size: ["XS", "X", "M"],
    price: "180",
  },
  {
    img: "assets/images/product1.png",
    rating: "4.8",
    brand: "Zara",
    title: "Quilted gilet with hood",
    color: ["Red", "Blue", "Black", "Pink", "Purple"],
    size: ["XS", "X", "M"],
    price: "180",
  },
  {
    img: "assets/images/product1.png",
    rating: "4.8",
    brand: "Zara",
    title: "Quilted gilet with hood",
    color: ["Red", "Blue", "Black", "Pink", "Purple"],
    size: ["XS", "X", "M"],
    price: "180",
  },
  {
    img: "assets/images/product1.png",
    rating: "4.8",
    brand: "Zara",
    title: "Quilted gilet with hood",
    color: ["Red", "Blue", "Black", "Pink", "Purple"],
    size: ["XS", "X", "M"],
    price: "180",
  },
];

module.exports = productData;
